"""
    Copyright (c) 2025 GregValiant (Greg Foresi)
    Suitable to Prusa, Orca, and Bambu slicers
    This script will:
        Add additional Gcode commands at layer changes.
        Delimit multiple commands with commas (EX:  M999,G92 E0,M221 S95)
    NOTE: Greg Valiant's "Add Layer Numbers" must run first.
"""

import sys
import os

# Get the file information from the slicer
sourceFile = sys.argv[1]
final_file = open(sourceFile, "r")
lines = final_file.readlines()
slicer_name = ""

# Let the user decide to run the script or exit without running.
response = "r"
while response == "r":
    response = input("\nGreg Valiant's      [Insert at Layer Change]\n for PrusaSlicer/OrcaSlicer/BambuStudio/CrealityPrint has started.\n  This will insert gcode commands every so-many layers.\nDo you wish to Continue?\n <y> Yes\n <n> No\n").lower()
    if response not in ["y", "n"]:
        fail_response = input("Invalid response.  It must be 'y' or 'n'.")
        response = "r"
        continue
    if response == "n":
        exit(0)

layer_count = 0        
for line in lines:
    if line.startswith(";Layer#:"):
        layer_count += 1

def main(lines):
    # Insert the post-processor name
    for index, line in enumerate(lines):
        if "; HEADER_BLOCK_END" in line or "; external perimeters extrusion width =" in line:
            lines.insert(index, ";     Post Processed by Greg Valiant's [Insert at Layer Change] for Prusa/Orca/Bambu/Creality\n")
            break
    support_enabled = None
    slicer_name = None
    for line in lines:
        if "generated by PrusaSlicer" in line:
            slicer_name = "Prusa"
        elif "generated by OrcaSlicer" in line:
            slicer_name = "Orca"
        elif "BambuStudio" in line:
            slicer_name = "Bambu"
        elif "Creality_Print" in line:
            slicer_name = "Creality"
        if slicer_name != None:
            break

    insert_frequency_str = ""
    while insert_frequency_str == "":
        insert_frequency_str = input(" 'Insertion Frequency'\n How often to insert the command.\n <enter an integer indicating: 0 for single insertion only, 1 for every layer, 2 for every other layer, 3 for every third layer, etc.\n <enter>\n")
        try:
            insert_frequency = int(insert_frequency_str)
        except:
            print("Invalid response.  Must be an integer.")
            insert_frequence_str = ""
            continue
    if insert_frequency > 0:        
        start_layer = 0
        while start_layer == 0:
            start_layer_str = input(f" 'The start layer'\n What layer should the insertions start at.  (the first layer is '1' and there are {layer_count} layers in the print.\n <enter>\n")
            try:
                start_layer = int(start_layer_str)
                if start_layer < 1:
                    start_layer_str = 0
                    print("Invalid response.  The layers start at layer 1.")
                    continue
            except:
                start_layer_str = 0
                print("Invalid response.  Try again.")
                continue
                
        end_layer_str = ""
        while end_layer_str == "":
            end_layer_str = input(f" 'The end layer'\n What layer should the insertions end at.\n  (there are {layer_count} layers in the print.\n <enter>\n")
            try:
                end_layer = int(end_layer_str)
                if end_layer > layer_count or end_layer <= start_layer:
                    end_layer_str = ""
                    print(f"Invalid response.  The entry must be > start layer ({start_layer}) and < top layer ({layer_count}).")
                    continue
            except:
                end_layer_str = ""
                print("Invalid response.  Try again.")
                continue
                
    elif insert_frequency == 0:        
        single_insert_layer_str = "0"
        while single_insert_layer_str == "0":
            single_insert_layer_str = input(" 'Single insertion Layer Number'\n For a one-time insertion, what is the layer number?\n <enter>\n")
            try:
                single_insert_layer = int(single_insert_layer_str)
                if single_insert_layer < 1:
                    print("Invalid response.  Must be an integer > 0.")
                    single_insert_layer_str = "0"
                    continue
            except:
                print("Invalid response.  Try again.")
                single_insert_layer_str = "0"
                continue

    gcode_to_add_str = ""
    while gcode_to_add_str == "":
        gcode_to_add_str = input(" 'Gcode to add'\n Enter the commands you wish to add.  If there are multiple commands then delimit each command with a comma.\n <enter>\n")
        gcode_to_add_list = []
        gcode_to_add = ""
        if "," in gcode_to_add_str:
            gcode_to_add_list = gcode_to_add_str.split(",")
        else:
            gcode_to_add_list.append(gcode_to_add_str)
        for index, gcode_cmd in enumerate(gcode_to_add_list):
            gcode_to_add += gcode_cmd.upper() + "\n"    
       
    #Initialize variables
    start_here = False
    real_num = 0
    past_first_0 = False
            
    # Insert the 'gcode_to_add' after the ';Layer:' line
    #Single insertion
    if insert_frequency == 0:    
        for index, line in enumerate(lines):
            if ";Layer#:" + str(single_insert_layer) + "\n" in line:
                lines.insert(index + 1, gcode_to_add)
                break
    #Multiple insertions
    else:
        layer_number = 0
        for l_index, line in enumerate(lines):
            if ";Layer#:" in line:
                layer_number = int(line.split(":")[1][:-1])
                if layer_number >= int(start_layer) and layer_number <= int(end_layer):
                    real_num = layer_number - int(start_layer)
                    if int(real_num / insert_frequency) - (real_num / insert_frequency) == 0:
                        lines[l_index] += gcode_to_add                
    
    # Split lines that have mid-line "\n" and insert them as their own item in "lines".
    for index, line in enumerate(lines):
        if "\n" in line[0:-1]:
            lines[index] = line[:-1]
            temp = lines.pop(index)
            temp1 = temp.split("\n")
            temp1.reverse()
            for n_line in temp1:
                lines.insert(index, n_line + "\n")

    # Write the new file
    dest_file = open(sourceFile, "w+")
    for line in lines:
        dest_file.write(line)
    dest_file.close()
    final_file.close()

# Define "main" so it will run.
if __name__ == "__main__":
    main(lines)