# Copyright (c) 2025 GregValiant (Greg Foresi)
#  Suitable to Prusa, Orca, and Bambu slicers
# This script will:
#    Add layer number lines below the "LAYER_CHANGE" lines.  The layer numbers coincide with the preview layers which can changed depending on whether or not supports are enabled.
#    Because of the variance in the layer count in the slicers, you should check your gcode to insure it is correct.
#    In addition to adding 'Layer: lines, the script will:
#       Remove empty lines.
#       Round the HEIGHT numbers to 3 decimal places and the WIPE numbers to 2 decimal places.

import sys
import os

# Get the file information from the slicer
sourceFile = sys.argv[1]
final_file = open(sourceFile, "r")
lines = final_file.readlines()
slicer_name = ""

# Let the user decide to run the script or exit without running.
response = "r"
while response == "r":
    response = input("\nGreg Valiant's      [Add Layer Numbers]\n Layer numbers are required for many post-processors.\n PLEASE NOTE: The layer count in Prusa/Orca/Bambu is a moving target and can vary depending on whether or not Supports are enabled.  The layer numbers generated by this script will show different results when 'Generate Support Material' is turned off, and when it is turned on.\n  Check the gcode to insure it is what you expected.\n Do you wish to continue?\n <y> Yes\n <n> No\n").lower()
    if response not in ["y", "n"]:
        input("Invalid response.  Enter a 'y' for Yes or an 'n' for No.")
        response = "r"
if response == "n":
    exit(0)

def main():
    # Insert the post-processor name
    for index, line in enumerate(lines):
        if "; HEADER_BLOCK_END" in line or "; external perimeters extrusion width =" in line:
            lines.insert(index, ";     Post Processed by Greg Valiant's [Add Layer Numbers] for Prusa/Orca/Bambu\n")
            break
    support_enabled = None
    slicer_name = None
    for line in lines:
        if "generated by PrusaSlicer" in line:
            slicer_name = "Prusa"
        elif "generated by OrcaSlicer" in line:
            slicer_name = "Orca"
        elif "BambuStudio" in line:
            slicer_name = "Bambu"
        if slicer_name != None:
            break

    # Start to do the actual post-processing
    if slicer_name != "Bambu":
        for line in lines:
            if "; first_layer_height =" in line:
                initial_layer_height = line.split("= ")[1]
            if "; layer_height =" in line:
                layer_height = line.split("= ")[1]
            if "; support_material =" in line or "; enable_support =" in line:
                support_enabled = bool(int(line.split("= ")[1][:-1]))
        hgt_line = ";HEIGHT:"
        wdt_line = ";WIDTH:"
        chg_line = ";LAYER_CHANGE"
        zee_line = ";Z:"
    elif slicer_name == "Bambu":
        for line in lines:
            if "; initial_layer_print_height =" in line:
                initial_layer_height = line.split("= ")[1]
            if "; layer_height =" in line:
                layer_height = line.split("= ")[1]
            if "; enable_support =" in line:
                support_enabled = bool(int(line.split("= ")[1][:-1]))
        hgt_line = "; Z_HEIGHT:"
        wdt_line = "; LINE_WIDTH:"
        chg_line = "; CHANGE_LAYER"
        zee_line = "; Z_HEIGHT:"

    # The slicers show different layer counts depending on whether or not Supports are generated.
    if support_enabled:
        lay_num = with_supports_enabled(initial_layer_height, layer_height, chg_line)
    elif not support_enabled or support_enabled == None:
        lay_num = with_supports_disabled(initial_layer_height, layer_height, chg_line, zee_line)

    # Finish up by removing empty lines and formatting long floats.
    for index, line in enumerate(lines):
        if line.startswith(hgt_line):
            hgt = float(line.split(":")[1])
            lines[index] = f"{hgt_line}{round(hgt, 3)}\n"
        # Format the 'WIDTH' lines so they are rounded to 2 decimal places
        if line.startswith(wdt_line):
            wdt = float(line.split(":")[1])
            lines[index] = f"{wdt_line}{round(wdt, 2)}\n"
        # Remove blank lines
        if line == "\n":
            lines[index] = ""
    for index, line in enumerate(lines):
        if chg_line in line:
            lines.insert(index + 1, f"; LAYER_COUNT:{lay_num - 1}\n" if slicer_name == "Bambu" else f";LAYER_COUNT:{lay_num - 1}\n")
            break
            
    # Inform the user of the layer count
    input("\n " + str(lay_num - 1) + " 'Layer:' lines were added.\n <enter> to continue\n")
    # Create the destination file and write the new code to it

    # Send the file back to the slicer as it was received, with each line a separate item in the lines list
    for index, line in enumerate(lines):
        if "\n" in line[0:-1]:
            lines[index] = line[:-1]
            temp = lines.pop(index)
            temp1 = temp.split("\n")
            temp1.reverse()
            for n_line in temp1:
                lines.insert(index, n_line + "\n")
    
    # Write the file
    dest_file = open(sourceFile, "w+")
    for line in lines:
        dest_file.write(line)
    dest_file.close()
    final_file.close()

def with_supports_disabled(initial_layer_height, layer_height, chg_line, zee_line):
    theory_z = round(float(initial_layer_height), 2)
    lay_z = round(float(layer_height), 2)
    lay_num = 1
    # Add the ';layer:#' lines below the 'LAYER_CHANGE' lines.  Some 'LAYER_CHANGE' lines may be skipped.
    for index, line in enumerate(lines):
        if chg_line in lines[index] and zee_line in lines[index + 1]:
            z_value = lines[index + 1].split(":")[1][:-1]
            if round(float(z_value), 2) >= round(theory_z, 2):
                lines.insert(index + 1, ";Layer:" + str(lay_num) + "\n")
                lay_num += 1
                theory_z = round(theory_z, 2) + lay_z
    return lay_num

def with_supports_enabled(initial_layer_height, layer_height, chg_line):
    lay_num = 1
    # Add the ';layer:#' lines below the 'LAYER_CHANGE' lines.
    for index, line in enumerate(lines):
        if chg_line in lines[index]:
            lines.insert(index + 1, ";Layer:" + str(lay_num) + "\n")
            lay_num += 1
    return lay_num

# Register 'main' so it will run
if __name__ == "__main__":
    main()