# By GregValiant (Greg Foresi) February 1, 2025
# This script will:
#    Add layer number lines below the "LAYER_CHANGE" lines.  The layer numbers coincide with the preview layers only when supports are turned off.
#        You may have to slice once with supports off to determine the preview layer numbers you want to act on, and then a second time for the gcode you want to print.
#    Remove empty lines.
#    Round the HEIGHT numbers to 3 decimal places and the WIPE numbers to 2 decimal places.

import sys
import os

# Get the file information from the slicer
sourceFile = sys.argv[1]
final_file = open(sourceFile, "r")
lines = final_file.readlines()

# Let the user decide to run the script or exit without running.
response = "r"
while response == "r":
    response = input("\nGreg Valiant's [Add Layer Numbers]\n Layer numbers are required for many post-processors.\n PLEASE NOTE: The layer count in Prusa is a moving target and can vary depending on whether or not Supports are enabled.  The layer numbers generated by this script will show different results when 'Generate Support Material' is turned off, and when it is turned on.\n  Check the gcode to insure it is what you expected.\n Do you wish to continue? (y) or (n).\n").lower()
    if response not in ["y", "n"]:
        input("Invalid response.  Enter a 'y' for Yes or an 'n' for No.")
        response = "r"
if response == "n":
    exit(0)

def __init__(self, lines, support_enabled, initial_layer_height, layer_height) -> None:
    self.with_supports_enabled()
    self.with_supports_disabled()
    lines = final_file.readlines()
    support_enabled
    initial_layer_height
    layer_height

def main():
    # Insert the post-processor name
    lines.insert(1, ";   Post Processed by Greg Valiant's [Add Layer Numbers] for Prusa/Orca\n")
    support_enabled = None
    # Start to do the actual post-processing
    for line in lines:
        if "; first_layer_height =" in line:
            initial_layer_height = line.split("= ")[1]
        if "; layer_height =" in line:
            layer_height = line.split("= ")[1]
        if "; support_material =" in line or "; enable_support =" in line:
            support_enabled = bool(int(line.split("= ")[1][:-1]))
    # Prusa shows different layer counts depending on whether or not Supports are generated.
    if support_enabled:
        lay_num = with_supports_enabled(initial_layer_height, layer_height)
    elif not support_enabled or support_enabled == None:
        lay_num = with_supports_disabled(initial_layer_height, layer_height)
        
    # Finish up by removing empty lines and formatting long floats.
    for index, line in enumerate(lines):
        if line.startswith(";HEIGHT:"):
            hgt = float(line.split(":")[1])
            lines[index] = f";HEIGHT:{round(hgt, 3)}\n"
        # Format the 'WIDTH' lines so they are rounded to 2 decimal places
        if line.startswith(";WIDTH:"):
            wdt = float(line.split(":")[1])
            lines[index] = f";WIDTH:{round(wdt, 2)}\n"
        # Remove blank lines
        if line == "\n":
            lines[index] = ""
    
    # Inform the user of the layer count
    input("\n " + str(lay_num - 1) + " 'Layer:' lines were added. <enter>\n")
    # Create the destination file and write the new code to it
    dest_file = open(sourceFile, "w+")
    for line in lines:
        dest_file.write(line)
    dest_file.close()
    final_file.close()

def with_supports_disabled(initial_layer_height, layer_height):
    theory_z = round(float(initial_layer_height), 2)
    lay_z = round(float(layer_height), 2)
    lay_num = 1
    # Add the ';layer:#' lines below the 'LAYER_CHANGE' lines.  Some 'LAYER_CHANGE' lines may be skipped.
    for index, line in enumerate(lines):
        if ";LAYER_CHANGE" in lines[index] and ";Z:" in lines[index + 1]:
            z_value = lines[index + 1].split(":")[1][:-1]
            if round(float(z_value), 2) >= round(theory_z, 2):
                lines.insert(index + 1, ";Layer:" + str(lay_num) + "\n")
                lay_num += 1
                theory_z = round(theory_z, 2) + lay_z
    return lay_num

def with_supports_enabled(initial_layer_height, layer_height):
    lay_num = 1
    # Add the ';layer:#' lines below the 'LAYER_CHANGE' lines.
    for index, line in enumerate(lines):
        if ";LAYER_CHANGE" in lines[index]:
            lines.insert(index + 1, ";Layer:" + str(lay_num) + "\n")
            lay_num += 1
    return lay_num

# Register 'main' so it will run
if __name__ == "__main__":
    main()