# By GregValiant (Greg Foresi) February 1, 2025
# This script will:
#    Add layer number lines below the "LAYER_CHANGE" lines.  The layer numbers coincide with the preview layers only when supports are turned off.
#        You may have to slice once with supports off to determine the preview layer numbers you want to act on, and then a second time for the gcode you want to print.
#    Remove empty lines.
#    Round the HEIGHT numbers to 3 decimal places and the WIPE numbers to 2 decimal places.

import sys
import os

# Get the file information from the slicer
sourceFile = sys.argv[1]
final_file = open(sourceFile, "r")
lines = final_file.readlines()

# Let the user decide to run the script or exit without running.
response = "r"
while response == "r":
    response = input("\nGreg Valiant's [Add Layer Numbers]\n Layer numbers are required for some post-processors.  Layers are numbered as per the 'Initial Layer Height' and the 'Layer Height' and start with ';Layer:1'.\n NOTE: The layer count in Prusa can vary depending on whether or not Supports are enabled.  The layer numbers generated by this script will match the layer numbers in the Prusa Preview when 'Generate Support Material' is turned off.\n You may need to slice twice; once with Supports turned off to find the 'real' layer numbers, and then slice again for the gcode you actually want to print.\n Do you wish to continue? (y) or (n).\n").lower()
    if response not in ["y", "n"]:
        input("Invalid response.  Enter a 'y' for Yes or an 'n' for No.")
        response = "r"
if response == "n":
    exit(0)

def main():
    # Insert the post-processor name
    lines.insert(1, ";   Post Processed by Greg Valiant's [Add Layer Numbers] for Prusa/Orca\n")

    # Start to do the actual post-processing
    for line in lines:
        if "; first_layer_height =" in line:
            initial_layer_height = line.split("= ")[1]
        if "; layer_height =" in line:
            layer_height = line.split("= ")[1]

    theory_z = round(float(initial_layer_height), 2)
    lay_z = round(float(layer_height), 2)
    lay_num = 1

    # Add the ';layer:#' lines below the 'LAYER_CHANGE' lines when the layer height it should be.  Some ';LAYER_CHANGE' lines will be skipped.
    for index, line in enumerate(lines):
        if ";LAYER_CHANGE" in lines[index] and ";Z:" in lines[index + 1]:
            z_value = lines[index + 1].split(":")[1][:-1]
            if round(float(z_value), 2) >= round(theory_z, 2):
                lines.insert(index + 1, ";Layer:" + str(lay_num) + "\n")
                lay_num += 1
                theory_z = round(theory_z, 2) + lay_z
        # Format the 'HEIGHT' lines so they are rounded to 3 decimal places
        if line.startswith(";HEIGHT:"):
            hgt = float(line.split(":")[1])
            lines[index] = f";HEIGHT:{round(hgt, 3)}\n"
        # Format the 'WIDTH' lines so they are rounded to 2 decimal places
        if line.startswith(";WIDTH:"):
            wdt = float(line.split(":")[1])
            lines[index] = f";WIDTH:{round(wdt, 2)}\n"
        # Remove blank lines
        if line == "\n":
            lines[index] = ""
    # Inform the user of the layer count
    input("\n " + str(lay_num - 1) + " 'Layer:' lines were added. <enter>\n")
    # Create the destination file and write the new code to it
    dest_file = open(sourceFile, "w+")
    for line in lines:
        dest_file.write(line)
    dest_file.close()
    final_file.close()

if __name__ == "__main__":
    main()